# data related
data_dir: "data"
src: "src"
tgt: "tgt"
src_max_seq: 40
tgt_max_seq: 12
src_vocab_size: 45000
tgt_vocab_size: 28000

# model, optimizer related
optim: "sgd"
lr: 1.0
lr_decay: 0.5
lr_decay_from: 8
weight_decay: 0.0
warmup_steps: 0
hidden_size: 8
bidirectional: True
src_embedding_size: 16
tgt_embedding_size: 16
num_layers: 2
dropout: 0.3

# training and evaluation related
beam_size: 3
batch_size: 32
max_epoch: 3
max_step: 2
random_seed: 111

# checkpoint and log related
experiment_name: "debug"
checkpoint_dir: "./checkpoints"
valid_step_interval: 1
train_step_interval: 1

